export const CLASS_NAMES = [
  "cars-bikes-people",
  "Bus",
  "Bushes",
  "Person",
  "Truck",
  "backpack",
  "bench",
  "bicycle",
  "boat",
  "branch",
  "car",
  "chair",
  "clock",
  "crosswalk",
  "door",
  "elevator",
  "fire_hydrant",
  "green_light",
  "gun",
  "handbag",
  "motorcycle",
  "person",
  "pothole",
  "rat",
  "red_light",
  "scooter",
  "sheep",
  "stairs",
  "stop_sign",
  "suitcase",
  "traffic light",
  "traffic_cone",
  "train",
  "tree",
  "truck",
  "umbrella",
  "yellow_light",
];

export const SPOKEN_NAMES: Record<string, string> = {
  "cars-bikes-people": "vehicle or person ahead",
  "Bus": "bus",
  "Bushes": "bushes",
  "Person": "person",
  "Truck": "truck",
  "backpack": "backpack",
  "bench": "bench",
  "bicycle": "bicycle",
  "boat": "boat",
  "branch": "branch",
  "car": "car",
  "chair": "chair",
  "clock": "clock",
  "crosswalk": "crosswalk",
  "door": "door",
  "elevator": "elevator",
  "fire_hydrant": "fire hydrant",
  "green_light": "green light",
  "gun": "gun, danger",
  "handbag": "handbag",
  "motorcycle": "motorcycle",
  "person": "person",
  "pothole": "pothole, watch your step",
  "rat": "rat",
  "red_light": "red light, stop",
  "scooter": "scooter",
  "sheep": "sheep",
  "stairs": "stairs ahead",
  "stop_sign": "stop sign",
  "suitcase": "suitcase",
  "traffic light": "traffic light",
  "traffic_cone": "traffic cone",
  "train": "train",
  "tree": "tree",
  "truck": "truck",
  "umbrella": "umbrella",
  "yellow_light": "yellow light",
};
